port: 5333
gitlab-uri: ""
gitlab-token: ""
telegram-bot-enabled: true
telegram-bot-token: ""
gitlab-namespaces:
  - public
log-to:
  - console
  - file
rolling-file-settings:
  file-name: logs/gitlab-ext.log
  max-size-mb: 30
  max-files: 3
  max-age-days: 14
  compress: true